---

- name: Converge
  hosts: all
  become: true
  tasks:
    - name: start the tasks
      ansible.builtin.include_tasks: tasks/main.yml
  handlers:
    - name: Reload bind
      ansible.builtin.service:
        name: "{{ bind_service }}"
        state: reloaded
      become: true
